"""Photo storage: compress + persist to the local filesystem.

Local-first contract: photos stay on the user's machine by default. We compress
aggressively (max 1024px, JPEG q78) before writing, mirroring the SKINFILE quota
lesson but now on the backend.
"""
import base64
import re
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageOps

from .config import settings

MAX_DIM = 1024
QUALITY = 78
# 縮圖用高少少嘅 quality：出嗰張相細，多幾個 byte 換少啲 JPEG 方塊。
THUMB_QUALITY = 82

# 縮圖只准呢幾個闊度。前端每個 render 位都用「兩倍 DPR」揀一格：
# composer 預覽 48 → 96、手機格 84 → 192（桌面格 96 都係 192）、手機日記 100 → 200、
# 手機對話氣泡 132 → 264、日記 148 → 296、桌面對話氣泡 168 → 336。
# 收窄成 whitelist 而唔係收任意 int，係唔想任何人叫 server 為咗每個數值
# 重新解碼一次 1024px JPEG（用 ?w=1..1024 逐個值＝CPU 放大攻擊）。
THUMB_WIDTHS = (96, 192, 200, 264, 296, 336)

# Photo ids are uuid4 hex generated by the upload endpoint. Restricting reads to
# that shape keeps arbitrary paths out of the filesystem lookup.
_PHOTO_ID = re.compile(r"^[0-9a-f]{32}$")


class UnreadableImage(Exception):
    """The uploaded bytes are not an image Pillow can open.

    Raised instead of letting `PIL.UnidentifiedImageError` escape: the upload route
    turns it into a readable 415, because the raw Pillow error reached the user as
    「✗ 上傳失敗：HTTP 500」(measured in-browser). The commonest real case is an iPhone
    HEIC file — Pillow without `pillow-heif` cannot open it, and HEIC is the *default*
    iPhone camera format, so "500 Internal Server Error" was the normal experience for
    an iPhone user uploading straight from the camera roll.
    """

    def __init__(self, detail: str):
        super().__init__(detail)
        self.detail = detail


def compress_image(data: bytes, max_dim: int = MAX_DIM, quality: int = QUALITY) -> bytes:
    """Decode → apply EXIF orientation → downscale → JPEG bytes.

    `ImageOps.exif_transpose` is load-bearing. A phone photo whose pixels are stored
    sideways with an EXIF orientation tag (the normal camera-roll case) used to be saved
    **unrotated with the tag dropped** — so the user's own preview *and* whatever the
    vision model received showed the face lying on its side. Measured with an
    orientation=6 fixture: 2048×1536 in → 1024×768 out, subject rotated ~90° (confirmed
    by reading the stored file back).
    """
    try:
        img = Image.open(BytesIO(data))
        img.load()
    except Exception as e:  # UnidentifiedImageError / truncated bytes / not an image
        raise UnreadableImage(f"{type(e).__name__}: {e}") from e
    img = ImageOps.exif_transpose(img) or img
    img = img.convert("RGB")
    img.thumbnail((max_dim, max_dim))
    out = BytesIO()
    img.save(out, "JPEG", quality=quality)
    return out.getvalue()


def save_photo(photo_id: str, data: bytes) -> str:
    """Persist a photo and return its path relative to the data dir."""
    compressed = compress_image(data)
    photos_dir = Path(settings.data_dir) / "photos"
    photos_dir.mkdir(parents=True, exist_ok=True)
    path = photos_dir / f"{photo_id}.jpg"
    path.write_bytes(compressed)
    return str(path.relative_to(settings.data_dir))


def photo_exists(photo_id: str) -> bool:
    """Whether a stored photo exists on disk (id-shape checked)."""
    if not _PHOTO_ID.match(photo_id):
        return False
    return (Path(settings.data_dir) / "photos" / f"{photo_id}.jpg").exists()


def thumb_jpeg(photo_id: str, width: int) -> bytes | None:
    """Downscaled JPEG for a stored photo, or None if the id/shape/file is wrong.

    Why this exists: a phone home screen renders 14 photos in **96×96** cells, and it
    used to fetch all of them at full size — measured **605.9 KB** for what the user
    sees as a contact sheet (each stored photo is 768×1024 / ~65 KB). The grid does not
    get sharper for those bytes: the CSS box is 96 px, so a 96–336 px thumb is already
    pixel-identical at 2× DPR.

    `width` must be one of `THUMB_WIDTHS` (the route enforces that); this function
    assumes it. Never upscales — a request wider than the stored file returns the
    stored dimensions.
    """
    if not _PHOTO_ID.match(photo_id):
        return None
    path = Path(settings.data_dir) / "photos" / f"{photo_id}.jpg"
    if not path.exists():
        return None
    with Image.open(path) as img:
        # JPEG DCT scaling：叫 decoder 直接用 1/2 或 1/4 解，唔使解全張 1024px。
        # 一定要喺 `convert()`（會 load 晒）之前 call。
        img.draft("RGB", (width, width))
        img = img.convert("RGB")
        if img.width > width:
            height = max(1, round(img.height * width / img.width))
            img = img.resize((width, height), Image.LANCZOS)
        out = BytesIO()
        img.save(out, "JPEG", quality=THUMB_QUALITY)
    return out.getvalue()


def load_photo_b64(photo_id: str) -> dict | None:
    """Return {media_type, data(base64)} for a stored photo, or None.

    Used ONLY for cloud vision analysis after the user has opted in (the
    conversation's cloud_analysis flag); photos are never read out otherwise.
    """
    if not _PHOTO_ID.match(photo_id):
        return None
    path = Path(settings.data_dir) / "photos" / f"{photo_id}.jpg"
    if not path.exists():
        return None
    return {"media_type": "image/jpeg", "data": base64.b64encode(path.read_bytes()).decode("ascii")}
