"""Photo storage: compress + persist to the local filesystem.

Local-first contract: photos stay on the user's machine by default. We compress
aggressively (max 1024px, JPEG q78) before writing, mirroring the SKINFILE quota
lesson but now on the backend.
"""
import base64
import re
from io import BytesIO
from pathlib import Path

from PIL import Image

from .config import settings

MAX_DIM = 1024
QUALITY = 78

# Photo ids are uuid4 hex generated by the upload endpoint. Restricting reads to
# that shape keeps arbitrary paths out of the filesystem lookup.
_PHOTO_ID = re.compile(r"^[0-9a-f]{32}$")


def compress_image(data: bytes, max_dim: int = MAX_DIM, quality: int = QUALITY) -> bytes:
    img = Image.open(BytesIO(data))
    img = img.convert("RGB")
    img.thumbnail((max_dim, max_dim))
    out = BytesIO()
    img.save(out, "JPEG", quality=quality)
    return out.getvalue()


def save_photo(photo_id: str, data: bytes) -> str:
    """Persist a photo and return its path relative to the data dir."""
    compressed = compress_image(data)
    photos_dir = Path(settings.data_dir) / "photos"
    photos_dir.mkdir(parents=True, exist_ok=True)
    path = photos_dir / f"{photo_id}.jpg"
    path.write_bytes(compressed)
    return str(path.relative_to(settings.data_dir))


def photo_exists(photo_id: str) -> bool:
    """Whether a stored photo exists on disk (id-shape checked)."""
    if not _PHOTO_ID.match(photo_id):
        return False
    return (Path(settings.data_dir) / "photos" / f"{photo_id}.jpg").exists()


def load_photo_b64(photo_id: str) -> dict | None:
    """Return {media_type, data(base64)} for a stored photo, or None.

    Used ONLY for cloud vision analysis after the user has opted in (the
    conversation's cloud_analysis flag); photos are never read out otherwise.
    """
    if not _PHOTO_ID.match(photo_id):
        return None
    path = Path(settings.data_dir) / "photos" / f"{photo_id}.jpg"
    if not path.exists():
        return None
    return {"media_type": "image/jpeg", "data": base64.b64encode(path.read_bytes()).decode("ascii")}
