"""Photo storage: compress + persist to the local filesystem.

Local-first contract: photos stay on the user's machine by default. We compress
aggressively (max 1024px, JPEG q78) before writing, mirroring the SKINFILE quota
lesson but now on the backend.
"""
import base64
import re
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageOps

from .config import settings

MAX_DIM = 1024
QUALITY = 78

# Photo ids are uuid4 hex generated by the upload endpoint. Restricting reads to
# that shape keeps arbitrary paths out of the filesystem lookup.
_PHOTO_ID = re.compile(r"^[0-9a-f]{32}$")


class UnreadableImage(Exception):
    """The uploaded bytes are not an image Pillow can open.

    Raised instead of letting `PIL.UnidentifiedImageError` escape: the upload route
    turns it into a readable 415, because the raw Pillow error reached the user as
    「✗ 上傳失敗：HTTP 500」(measured in-browser). The commonest real case is an iPhone
    HEIC file — Pillow without `pillow-heif` cannot open it, and HEIC is the *default*
    iPhone camera format, so "500 Internal Server Error" was the normal experience for
    an iPhone user uploading straight from the camera roll.
    """

    def __init__(self, detail: str):
        super().__init__(detail)
        self.detail = detail


def compress_image(data: bytes, max_dim: int = MAX_DIM, quality: int = QUALITY) -> bytes:
    """Decode → apply EXIF orientation → downscale → JPEG bytes.

    `ImageOps.exif_transpose` is load-bearing. A phone photo whose pixels are stored
    sideways with an EXIF orientation tag (the normal camera-roll case) used to be saved
    **unrotated with the tag dropped** — so the user's own preview *and* whatever the
    vision model received showed the face lying on its side. Measured with an
    orientation=6 fixture: 2048×1536 in → 1024×768 out, subject rotated ~90° (confirmed
    by reading the stored file back).
    """
    try:
        img = Image.open(BytesIO(data))
        img.load()
    except Exception as e:  # UnidentifiedImageError / truncated bytes / not an image
        raise UnreadableImage(f"{type(e).__name__}: {e}") from e
    img = ImageOps.exif_transpose(img) or img
    img = img.convert("RGB")
    img.thumbnail((max_dim, max_dim))
    out = BytesIO()
    img.save(out, "JPEG", quality=quality)
    return out.getvalue()


def save_photo(photo_id: str, data: bytes) -> str:
    """Persist a photo and return its path relative to the data dir."""
    compressed = compress_image(data)
    photos_dir = Path(settings.data_dir) / "photos"
    photos_dir.mkdir(parents=True, exist_ok=True)
    path = photos_dir / f"{photo_id}.jpg"
    path.write_bytes(compressed)
    return str(path.relative_to(settings.data_dir))


def photo_exists(photo_id: str) -> bool:
    """Whether a stored photo exists on disk (id-shape checked)."""
    if not _PHOTO_ID.match(photo_id):
        return False
    return (Path(settings.data_dir) / "photos" / f"{photo_id}.jpg").exists()


def load_photo_b64(photo_id: str) -> dict | None:
    """Return {media_type, data(base64)} for a stored photo, or None.

    Used ONLY for cloud vision analysis after the user has opted in (the
    conversation's cloud_analysis flag); photos are never read out otherwise.
    """
    if not _PHOTO_ID.match(photo_id):
        return None
    path = Path(settings.data_dir) / "photos" / f"{photo_id}.jpg"
    if not path.exists():
        return None
    return {"media_type": "image/jpeg", "data": base64.b64encode(path.read_bytes()).decode("ascii")}
